### ISSUE TITLE
add option to check integrity/authenticity

### ISSUE THREAD

**Issue by luclu** [ethereum/ethereum-client-binaries#1]
For SWARM and IPFS this won't be necessary, as the address hashes also validate it.

**Comment by hiddentao** [comment]
We should use the same hashing mechanism as Swarm/IPFS to minimize code to add.

**Comment by luclu** [comment]
I think just an optional field for a sha256 checksum plus the internal check routines in the code should do it.

**Comment by hiddentao** [comment]
I want to implement this next to ensure security of the binaries.

**Comment by hiddentao** [comment]
Will do SHA256.

**Comment by hiddentao** [comment]
Done in 1.5.0.
